### ISSUE TITLE
tools/evalSAD.sh

### ISSUE THREAD

**Issue by riebling** [aclew/tools#1]
My system is creating outputs /vagrant/data/noisemes_sad_basename.rttm
But the evalSAD.sh script checks for files with noiseme_sad_basename.rttm pattern of name. Which is right, noiseme, or noisemes?

**Comment by riebling** [comment]
This seems to work now.
I thought I had created an issue about errors with evalSAD.sh and filenames not found like `DH_0053..lab` - but it seems my temp_sys had many wrong filenames in it probably from my incorrectly running evalSAD.sh previously. (files like `DH_0071.` and `DH_0071..lab`)

Clearing out the ldc_sad_eval/ folder fixed this.
It now produces a reasonable looking data/ldc_sad_eval.df - thanks!

**Comment by riebling** [comment]
Yipes a different problem, two, one easy, one hard.
Easy: usage message should match usage "noisemes"
But the harder to fix (maybe my data is bad?):
```
vagrant@vagrant-ubuntu-trusty-64:~/tools$ ./evalSAD.sh data noisemes
evaluating
score.py:118: RuntimeWarning: invalid value encountered in double_scalars
  fa_rate = 100*(fa_dur / ref_nonspeech_dur)
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 115, in score_files
    durs = [score_file(**kwargs) for kwargs in kwargs_gen()]
  File "score.py", line 96, in score_file
    dur = min(sys_segs[-1][1], ref_segs[-1][1])
IndexError: list index out of range
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 115, in score_files
    durs = [score_file(**kwargs) for kwargs in kwargs_gen()]
  File "score.py", line 96, in score_file
    dur = min(sys_segs[-1][1], ref_segs[-1][1])
IndexError: list index out of range
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 115, in score_files
    durs = [score_file(**kwargs) for kwargs in kwargs_gen()]
  File "score.py", line 96, in score_file
    dur = min(sys_segs[-1][1], ref_segs[-1][1])
IndexError: list index out of range
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 115, in score_files
    durs = [score_file(**kwargs) for kwargs in kwargs_gen()]
  File "score.py", line 96, in score_file
    dur = min(sys_segs[-1][1], ref_segs[-1][1])
IndexError: list index out of range
done evaluating, check data/noisemes_sad_eval.df for the results
```

**Comment by riebling** [comment]
haha re-closing my own issue again - these errors are apparently ok, some nan were produced as output I think is the only effect of the errors
